### PR TITLE
move ecli (cpp version) to ecli/minimal

### PR DESCRIPTION
**Pull request by try-agaaain**
move ecli/ecli-rs to ecli, and move ecli (cpp version) to ecli/minimal.

link to first task of issue[#119](https://github.com/eunomia-bpf/eunomia-bpf/issues/119)

### CODE REVIEW

**Comment by try-agaaain** [comment]
In my personal repository's CI tests, the submitted code has successfully passed the tests for the compiler, BPF-loader, ecli, and wasm-runtime.

image

At the same time, the ecli image can also be built normally with ci.

**Comment by yunwei37** [comment]
Thanks！You need to resolve conflicts before merge.

In your next PR, the contents in `ecli/ecli-rs/` need to be moved to `ecli/`, as the default version of ecli runner?

**Review by yunwei37 — CHANGES_REQUESTED** [review]
Please resolve the conflicts.

**Comment by try-agaaain** [comment]
> Thanks！You need to resolve conflicts before merge.
> 
> In your next PR, the contents in `ecli/ecli-rs/` need to be moved to `ecli/`, as the default version of ecli runner?

Thank you for the reminder, I will move the content of ecli/ecli-rs/ to ecli in the next PR.

**Comment by try-agaaain** [comment]
There is a failing check detected by CodeQL, is it necessary to fix it?

**Comment by yunwei37** [comment]
Please fix it if it's possible.

**Review by yunwei37 — APPROVED** [review]

**Pull request merged**
