### PR TITLE
Merge ecli and ecc docker image

### PR DESCRIPTION
**Pull request by ocfox**
Merge the dockerfile, it will increase the size of the docker image, but significantly reduce maintenance costs and improve availability.
The new docker image includes ecc and ecli.
Run with whatever -v -i or other flag.
```
docker run eunomia-x86_64:latest ecli
docker run eunomia-aarch64:latest ecc
```
This change needs to be discussed, mentioning @yunwei37 @try-agaaain @Officeyutong @oluceps.
The main reason for this change is that the docker build cannot copy files outside the directory, which prevents the ecli dockerfile from being generic.
Also don't need to worry about image size, compared with the previous ecc image, this image only adds an ecli binary(by using multi-stage builds).

### CODE REVIEW

**Comment by ocfox** [comment]
> so why not add ecli to ecc image，while make another ecli docker alone?

In fact, that's what this change does, just renamed the merged docker.

**Comment by yunwei37** [comment]
I think it's not a good idea to rename and merge the docker. ecli user does not need the ecc images

**Comment by ocfox** [comment]
Yes, this will add unnecessary image size for ecli users, maybe with docker-compose.
But in any case, I think that is not a way to simply copy ecli in docker.

https://github.com/eunomia-bpf/eunomia-bpf/blob/ef25c0d6df844d13f12eb93aa7d246df211f5c4f/ecli/dockerfile#L6-L10

**Comment by Officeyutong** [comment]
What's going on now?

**Comment by Officeyutong** [comment]
Does ecli really require a docker image?

**Comment by ocfox** [comment]
Yes, here is no reason to run the bpf program in docker.

**Pull request closed without merging**
